environment:
  matrix:
    - nodejs_version: "6.14"
    - nodejs_version: "8.10"
    - nodejs_version: "9.10"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
